environment:
  sonar_login:
    secure: GRQOT/Rl3Xn8lskpEWsQuc0ejmh1Xi0CP2BZ7tWi2eo8p8XgVfekFdbYMRz4QVZJ
version: 0.0.1.{build}
skip_tags: true
skip_commits:
  files:
    - CHANGELOG.MD
    - LICENSE
    - README.MD
os: Visual Studio 2015
platform: Any CPU
configuration: Release
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
  assembly_informational_version: $(appveyor_build_version)
before_build:
  - nuget restore src\Logikfabrik.Overseer.sln
build_script:
  - choco install "msbuild-sonarqube-runner" -y
  - SonarQube.Scanner.MSBuild.exe begin /k:"overseer" /o:"logikfabrik-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="%sonar_login%" /d:sonar.projectBaseDir="/src" /d:sonar.cs.opencover.reportsPaths="results.xml" /v:%appveyor_build_version%
  - msbuild src\Logikfabrik.Overseer.sln /p:Configuration=%configuration% /p:InstallerVersion=%appveyor_build_version% /p:WarningLevel=1 -verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - choco install "opencover.portable" -y
  - OpenCover.Console.exe "-register:user" "-target:powershell.exe" "-targetargs:-File C:\projects\overseer\xunit.ps1"
  - SonarQube.Scanner.MSBuild.exe end /d:sonar.login="%sonar_login%"
artifacts:
  - path: src\Logikfabrik.Overseer.Setup\bin\$(configuration)\*.msi
    name: Setup
test:
  assemblies:
    - '**\*.Test.dll'