version: 0.0.1.{build}
skip_tags: true
os: Visual Studio 2015
platform: Any CPU
configuration: Release
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
before_build:
- nuget restore src/Logikfabrik.Overseer.sln
build_script:
  - msbuild src/Logikfabrik.Overseer.sln /p:Configuration=%configuration% /p:InstallerVersion=%version% /p:WarningLevel=1 -verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
  - path: src/Logikfabrik.Overseer.Setup/bin/$(configuration)/*.msi
    name: Setup
test:
  assemblies:
    - '**\*.Test.dll'