version: 0.0.1.{build}
skip_tags: true
skip_commits:
  files:
    - CHANGELOG.MD
    - LICENSE
    - README.MD
os: Visual Studio 2015
platform: Any CPU
configuration: Release
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
  assembly_informational_version: $(appveyor_build_version)
before_build:
- nuget restore src/Logikfabrik.Overseer.sln
build_script:
  - msbuild src/Logikfabrik.Overseer.sln /p:Configuration=%configuration% /p:InstallerVersion=%appveyor_build_version% /p:WarningLevel=1 -verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
  - path: src/Logikfabrik.Overseer.Setup/bin/$(configuration)/*.msi
    name: Setup
test:
  assemblies:
    - '**\*.Test.dll'