environment:
  sonar_login:
    secure: wA8dX4gVDmyoUNjC+y37ygfPAekg/EyWs7Z7SkRp8vDr1Vv7oBB9R6nif4yzRza4
version: 0.0.1.{build}
skip_tags: true
skip_commits:
  files:
    - CHANGELOG.MD
    - LICENSE
    - README.MD
os: Visual Studio 2015
platform: Any CPU
configuration: Release
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
  assembly_informational_version: $(appveyor_build_version)
before_build:
  - nuget restore src\Logikfabrik.Overseer.sln
build_script: 
  - choco install "msbuild-sonarqube-runner" -y
  - choco install "opencover.portable" -y
  - SonarQube.Scanner.MSBuild.exe begin /k:"overseer" /o:"logikfabrik-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="%sonar_login%" /d:sonar.projectBaseDir="src" /d:sonar.cs.opencover.reportsPaths="results.xml" /v:%appveyor_build_version%
  - msbuild src\Logikfabrik.Overseer.sln /p:Configuration=%configuration% /p:InstallerVersion=%appveyor_build_version% /p:WarningLevel=1 -verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - OpenCover.Console.exe -register:user -target:"xunit.console.clr4" -targetargs:"'**\*.Test.dll' /appveyor"
  - SonarQube.Scanner.MSBuild.exe end /d:sonar.login="%sonar_login%"
artifacts:
  - path: src\Logikfabrik.Overseer.Setup\bin\$(configuration)/*.msi
    name: Setup