//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logikfabrik.Overseer.WPF.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Logikfabrik.Overseer.WPF.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AddConnection_Button_Add {
            get {
                return ResourceManager.GetString("AddConnection_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AddConnection_Button_Cancel {
            get {
                return ResourceManager.GetString("AddConnection_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to connect.
        /// </summary>
        public static string AddConnection_Button_TryConnect {
            get {
                return ResourceManager.GetString("AddConnection_Button_TryConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add connection.
        /// </summary>
        public static string AddConnection_View {
            get {
                return ResourceManager.GetString("AddConnection_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add connection.
        /// </summary>
        public static string Connections_Tile_Button_Add {
            get {
                return ResourceManager.GetString("Connections_Tile_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no connections. Get started by adding one..
        /// </summary>
        public static string Connections_Tile_Message_NoConnections {
            get {
                return ResourceManager.GetString("Connections_Tile_Message_NoConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string EditConnection_Button_Cancel {
            get {
                return ResourceManager.GetString("EditConnection_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string EditConnection_Button_Edit {
            get {
                return ResourceManager.GetString("EditConnection_Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to connect.
        /// </summary>
        public static string EditConnection_Button_TryConnect {
            get {
                return ResourceManager.GetString("EditConnection_Button_TryConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit connection.
        /// </summary>
        public static string EditConnection_View {
            get {
                return ResourceManager.GetString("EditConnection_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of builds to get from the CI/DI service per project.
        /// </summary>
        public static string EditConnectionSettings_Setting_Description_BuildsPerProject {
            get {
                return ResourceManager.GetString("EditConnectionSettings_Setting_Description_BuildsPerProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builds per project.
        /// </summary>
        public static string EditConnectionSettings_Setting_Label_BuildsPerProject {
            get {
                return ResourceManager.GetString("EditConnectionSettings_Setting_Label_BuildsPerProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string EditConnectionSettings_Setting_Label_TrackedProjects {
            get {
                return ResourceManager.GetString("EditConnectionSettings_Setting_Label_TrackedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string EditSettings_Button_Cancel {
            get {
                return ResourceManager.GetString("EditSettings_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string EditSettings_Button_Save {
            get {
                return ResourceManager.GetString("EditSettings_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing language will restart the program.
        /// </summary>
        public static string EditSettings_Setting_Description_CultureName {
            get {
                return ResourceManager.GetString("EditSettings_Setting_Description_CultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (s) between updates.
        /// </summary>
        public static string EditSettings_Setting_Description_Interval {
            get {
                return ResourceManager.GetString("EditSettings_Setting_Description_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string EditSettings_Setting_Label_CultureName {
            get {
                return ResourceManager.GetString("EditSettings_Setting_Label_CultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string EditSettings_Setting_Label_Interval {
            get {
                return ResourceManager.GetString("EditSettings_Setting_Label_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit settings.
        /// </summary>
        public static string EditSettings_View {
            get {
                return ResourceManager.GetString("EditSettings_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all.
        /// </summary>
        public static string EditTrackedProjects_Button_DeselectAll {
            get {
                return ResourceManager.GetString("EditTrackedProjects_Button_DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string EditTrackedProjects_Button_Filter {
            get {
                return ResourceManager.GetString("EditTrackedProjects_Button_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string EditTrackedProjects_Button_SelectAll {
            get {
                return ResourceManager.GetString("EditTrackedProjects_Button_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Menu_MenuItem_Label_GoToAbout {
            get {
                return ResourceManager.GetString("Menu_MenuItem_Label_GoToAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string Menu_MenuItem_Label_GoToConnections {
            get {
                return ResourceManager.GetString("Menu_MenuItem_Label_GoToConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Menu_MenuItem_Label_GoToDashboard {
            get {
                return ResourceManager.GetString("Menu_MenuItem_Label_GoToDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_MenuItem_Label_GoToSettings {
            get {
                return ResourceManager.GetString("Menu_MenuItem_Label_GoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string RemoveConnection_Button_Cancel {
            get {
                return ResourceManager.GetString("RemoveConnection_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string RemoveConnection_Button_Remove {
            get {
                return ResourceManager.GetString("RemoveConnection_Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribution.
        /// </summary>
        public static string ViewAbout_Setting_Label_Attribution {
            get {
                return ResourceManager.GetString("ViewAbout_Setting_Label_Attribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string ViewAbout_Setting_Label_Version {
            get {
                return ResourceManager.GetString("ViewAbout_Setting_Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ViewConnection_Button_Edit {
            get {
                return ResourceManager.GetString("ViewConnection_Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string ViewConnection_Button_Filter {
            get {
                return ResourceManager.GetString("ViewConnection_Button_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ViewConnection_Button_Remove {
            get {
                return ResourceManager.GetString("ViewConnection_Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no projects for this connection.
        /// </summary>
        public static string ViewConnection_Message_NoProjects {
            get {
                return ResourceManager.GetString("ViewConnection_Message_NoProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest build.
        /// </summary>
        public static string ViewProject_Tile_Label_LatestBuild {
            get {
                return ResourceManager.GetString("ViewProject_Tile_Label_LatestBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued builds.
        /// </summary>
        public static string ViewProject_Tile_Label_QueuedBuilds {
            get {
                return ResourceManager.GetString("ViewProject_Tile_Label_QueuedBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no builds for this project.
        /// </summary>
        public static string ViewProject_Tile_Message_NoBuilds {
            get {
                return ResourceManager.GetString("ViewProject_Tile_Message_NoBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string WizardEditPassphrase_Button_NextStep {
            get {
                return ResourceManager.GetString("WizardEditPassphrase_Button_NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s start with a passphrase.
        /// </summary>
        public static string WizardEditPassphrase_Heading {
            get {
                return ResourceManager.GetString("WizardEditPassphrase_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll use it to encrypt your settings.
        /// </summary>
        public static string WizardEditPassphrase_Text {
            get {
                return ResourceManager.GetString("WizardEditPassphrase_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string WizardFinish_Button_Finish {
            get {
                return ResourceManager.GetString("WizardFinish_Button_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m ready.
        /// </summary>
        public static string WizardFinish_Heading {
            get {
                return ResourceManager.GetString("WizardFinish_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WizardFinish_Text {
            get {
                return ResourceManager.GetString("WizardFinish_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string WizardStart_Button_NextStep {
            get {
                return ResourceManager.GetString("WizardStart_Button_NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, I&apos;m Overseer.
        /// </summary>
        public static string WizardStart_Heading {
            get {
                return ResourceManager.GetString("WizardStart_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll help track your builds.
        /// </summary>
        public static string WizardStart_Text {
            get {
                return ResourceManager.GetString("WizardStart_Text", resourceCulture);
            }
        }
    }
}
