//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logikfabrik.Overseer.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Logikfabrik.Overseer.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there seems to be a problem!
        ///We couldn&apos;t connect to the CI/CD service. Please check your settings and try again..
        /// </summary>
        public static string AddConnection_Error_HTTP4xx {
            get {
                return ResourceManager.GetString("AddConnection_Error_HTTP4xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there seems to be a problem!
        ///We couldn&apos;t connect to the CI/CD service. Please check your settings, and CI/CD service, and try again..
        /// </summary>
        public static string AddConnection_Error_HTTP5xx {
            get {
                return ResourceManager.GetString("AddConnection_Error_HTTP5xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there seems to be a problem!
        ///We couldn&apos;t connect to the CI/CD service. Please check your network connection and try again..
        /// </summary>
        public static string AddConnection_Error_Network {
            get {
                return ResourceManager.GetString("AddConnection_Error_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there seems to be a problem!
        ///We couldn&apos;t connect to the CI/CD service. Please try again..
        /// </summary>
        public static string AddConnection_Error_Standard {
            get {
                return ResourceManager.GetString("AddConnection_Error_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add connection.
        /// </summary>
        public static string AddConnection_View {
            get {
                return ResourceManager.GetString("AddConnection_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there seems to be a problem!
        ///Please try again..
        /// </summary>
        public static string App_Error_Standard {
            get {
                return ResourceManager.GetString("App_Error_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there seems to be a problem!
        ///We couldn&apos;t connect to the CI/CD service. Please check your settings and try again..
        /// </summary>
        public static string EditConnection_Error_HTTP4xx {
            get {
                return ResourceManager.GetString("EditConnection_Error_HTTP4xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there seems to be a problem!
        ///We couldn&apos;t connect to the CI/CD service. Please check your settings, and CI/CD service, and try again..
        /// </summary>
        public static string EditConnection_Error_HTTP5xx {
            get {
                return ResourceManager.GetString("EditConnection_Error_HTTP5xx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there seems to be a problem!
        ///We couldn&apos;t connect to the CI/CD service. Please check your network connection and try again..
        /// </summary>
        public static string EditConnection_Error_Network {
            get {
                return ResourceManager.GetString("EditConnection_Error_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there seems to be a problem!
        ///We couldn&apos;t connect to the CI/CD service. Please try again..
        /// </summary>
        public static string EditConnection_Error_Standard {
            get {
                return ResourceManager.GetString("EditConnection_Error_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit connection.
        /// </summary>
        public static string EditConnection_View {
            get {
                return ResourceManager.GetString("EditConnection_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builds per project can be between 1 and 10.
        /// </summary>
        public static string EditConnectionSettings_Validation_BuildsPerProject_InclusiveBetween {
            get {
                return ResourceManager.GetString("EditConnectionSettings_Validation_BuildsPerProject_InclusiveBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have to get at least 1 build per project.
        /// </summary>
        public static string EditConnectionSettings_Validation_BuildsPerProject_NotEmpty {
            get {
                return ResourceManager.GetString("EditConnectionSettings_Validation_BuildsPerProject_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is missing.
        /// </summary>
        public static string EditConnectionSettings_Validation_Name_NotEmpty {
            get {
                return ResourceManager.GetString("EditConnectionSettings_Validation_Name_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language is missing.
        /// </summary>
        public static string EditSettings_Validation_CultureName {
            get {
                return ResourceManager.GetString("EditSettings_Validation_CultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval can be between 10 and 86400 (24 hours).
        /// </summary>
        public static string EditSettings_Validation_Interval_InclusiveBetween {
            get {
                return ResourceManager.GetString("EditSettings_Validation_Interval_InclusiveBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval is missing.
        /// </summary>
        public static string EditSettings_Validation_Interval_NotEmpty {
            get {
                return ResourceManager.GetString("EditSettings_Validation_Interval_NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string EditSettings_View {
            get {
                return ResourceManager.GetString("EditSettings_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CI/CD service.
        /// </summary>
        public static string NewConnection_View {
            get {
                return ResourceManager.GetString("NewConnection_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove connection.
        /// </summary>
        public static string RemoveConnection_View {
            get {
                return ResourceManager.GetString("RemoveConnection_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ViewAbout_View {
            get {
                return ResourceManager.GetString("ViewAbout_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string ViewConnection_View {
            get {
                return ResourceManager.GetString("ViewConnection_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string ViewConnections_View {
            get {
                return ResourceManager.GetString("ViewConnections_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string ViewDashboard_View {
            get {
                return ResourceManager.GetString("ViewDashboard_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ViewProject_View {
            get {
                return ResourceManager.GetString("ViewProject_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase is too short.
        /// </summary>
        public static string WizardEditPassphrase_Validation_Passphrase_MinimumLength {
            get {
                return ResourceManager.GetString("WizardEditPassphrase_Validation_Passphrase_MinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase is missing.
        /// </summary>
        public static string WizardEditPassphrase_Validation_Passphrase_NotEmpty {
            get {
                return ResourceManager.GetString("WizardEditPassphrase_Validation_Passphrase_NotEmpty", resourceCulture);
            }
        }
    }
}
